encryptionMethod=public static byte[] xor(byte[] data){byte[] key = Convert.FromBase64String("{xorKey}");int len = data.Length;int keyLen = key.Length;int index = 0;for(int i = 1; i <= len; i++){index = i - 1;data[index] =(byte)(data[index] ^ key[(i % keyLen)]);}return data;}
variable=
encryptionCallMethod=responseData = xor(responseData);
decryptionCallMethod=requestData = xor(requestData);
