encryptionMethod=function xorEncrypt(&$data){$key=base64_decode("{xorKey}");$len=strlen($data);$keyLen=strlen($key);$index=0;for($i=1;$i <=$len;$i++){$index=$i-1;$data[$index]=$data[$index]^$key[($i%$keyLen)];}}
variable=
encryptionCallMethod=xorEncrypt($responseData);
decryptionCallMethod=xorEncrypt($requestData);
