encryptionMethod= public byte[] aes256(byte[] s, int mode) { try { javax.crypto.Cipher c = javax.crypto.Cipher.getInstance("AES/CBC/PKCS5Padding"); javax.crypto.spec.IvParameterSpec ivParameterSpec =new javax.crypto.spec.IvParameterSpec(base64Decode("{aes256IV}".getBytes())); c.init(mode, new javax.crypto.spec.SecretKeySpec(base64Decode("{aes256Key}".getBytes()),"AES"),ivParameterSpec); return c.doFinal(s); } catch (Exception e) { return null; } }
variable=
encryptionCallMethod=responseData = aes256(responseData, 1);
decryptionCallMethod=requestData = aes256(requestData, 2);
