encryptionMethod=
variable=
encryptionCallMethod=responseData = System.Text.Encoding.Default.GetBytes(Convert.ToBase64String(responseData));
decryptionCallMethod=requestData = Convert.FromBase64String(System.Text.Encoding.Default.GetString(requestData));
