encryptionMethod=public byte[] aes128(byte[] s, int mode){try{javax.crypto.Cipher c = javax.crypto.Cipher.getInstance("AES"); c.init(mode, new javax.crypto.spec.SecretKeySpec(base64Decode("{aes128Key}".getBytes()), "AES")); return c.doFinal(s);}catch(Exception e){return null;}}
variable=
encryptionCallMethod=responseData = aes128(responseData, 1);
decryptionCallMethod=requestData = aes128(requestData, 2);
