variable=
encryptionCallMethod=responseData = java.net.URLEncoder.encode(new String(responseData)).getBytes();
decryptionCallMethod=requestData = java.net.URLDecoder.decode(new String(requestData)).getBytes();
